schema_version: 1

context:
  name: pytokens
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytokens-${{ version }}.tar.gz
  sha256: 6b0b03e6ea7c9f9d47c5c61164b69ad30f4f0d70a5d9fe7eac4d19f24f77af2d

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - setuptools
    - mypyc
  run:
    - python

tests:
  - python:
      imports:
        - pytokens
      pip_check: true

about:
  summary: A Fast, spec compliant Python 3.14+ tokenizer that runs on older Pythons.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tusharsadhwani/pytokens

extra:
  recipe-maintainers:
    - xhochy
